theme: jekyll-theme-minimal
title: GitHub pages template
description: A simple template based on minimal jekyll theme
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Link to file2
    url: file2
 - title: Another home link
    url: /
