theme: jekyll-theme-minimal
title: Testing another template
description: foo and bar
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Link to file2
    url: file2
 - title: Another home link
    url: /
